env:
  CPPFLAGS: -I/usr/local/include
  LDFLAGS: -L/usr/local/lib
  BIRCH_MODE: debug
  OMP_NUM_THREADS: 4
  MODE_FLAGS: '--enable-debug --disable-test --disable-release'
  BIRCH_FLAGS: '--unit=unity --arch=native --jobs=4 --enable-verbose'

task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-12-2
    cpu: 8
    memory: 16G
  install_script:
    - pkg install -y bash m4 autoconf automake elfutils flex bison boost-libs cairo eigen libtool libyaml sqlite3
  birch_build_script:
    - cd birch
    - ./bootstrap
    - ./configure CXXFLAGS="-Wall -Wno-overloaded-virtual -g -O0 -fno-inline --coverage" || cat config.log
    - make -j4
    - sudo make install
    - bash ./smoke.sh
  numbirch_build_script:
    - cd numbirch
    - ./bootstrap
    - ./configure ${MODE_FLAGS} || cat config.log
    - make -j4
    - sudo make install
  membirch_build_script:
    - cd membirch
    - ./bootstrap
    - ./configure ${MODE_FLAGS} || cat config.log
    - make -j4
    - sudo make install
  birch-standard_build_script:
    - cd libraries/Standard
    - birch build ${MODE_FLAGS} ${BIRCH_FLAGS} || cat config.log
    - sudo make install
  birch-cairo_build_script:
    - cd libraries/Cairo
    - birch build ${MODE_FLAGS} ${BIRCH_FLAGS} || cat config.log
    - sudo make install
  birch-sqlite_build_script:
    - cd libraries/SQLite
    - birch build ${MODE_FLAGS} ${BIRCH_FLAGS} || cat config.log
    - sudo make install
  birch-standard_test_build_script:
    - cd libraries/StandardTest
    - birch build ${MODE_FLAGS} ${BIRCH_FLAGS} || cat config.log
    - bash ./smoke.sh
  LinearRegression_build_script:
    - cd examples/LinearRegression
    - birch build ${MODE_FLAGS} ${BIRCH_FLAGS} || cat config.log
    - bash ./smoke.sh
  LinearGaussian_build_script:
    - cd examples/LinearGaussian
    - birch build ${MODE_FLAGS} ${BIRCH_FLAGS} || cat config.log
    - bash ./smoke.sh
  MixedGaussian_build_script:
    - cd examples/MixedGaussian
    - birch build ${MODE_FLAGS} ${BIRCH_FLAGS} || cat config.log
    - bash ./smoke.sh
  PoissonGaussian_build_script:
    - cd examples/PoissonGaussian
    - birch build ${MODE_FLAGS} ${BIRCH_FLAGS} || cat config.log
    - bash ./smoke.sh
  SIR_build_script:
    - cd examples/SIR
    - birch build ${MODE_FLAGS} ${BIRCH_FLAGS} || cat config.log
    - bash ./smoke.sh
  VectorBorneDisease_build_script:
    - cd examples/VectorBorneDisease
    - birch build ${MODE_FLAGS} ${BIRCH_FLAGS} || cat config.log
    - bash ./smoke.sh
  MultiObjectTracking_build_script:
    - cd examples/MultiObjectTracking
    - birch build ${MODE_FLAGS} ${BIRCH_FLAGS} || cat config.log
    - bash ./smoke.sh
  Ecology_build_script:
    - cd examples/Ecology
    - birch build ${MODE_FLAGS} ${BIRCH_FLAGS} || cat config.log
    - bash ./smoke.sh
