coverage:
  precision: 2
  round: nearest
  range: "60...90"
status:
  project:
    default:
      target: auto
      threshold: 3%
      if_not_found: success
      if_ci_failed: error
      informational: true
      only_pulls: false
