site_name: 'Birch Documentation'
site_description: 'An open source probabilistic programming language that combines automatic differentiation, automatic marginalization, automatic conjugacy, and a Sequential Monte Carlo (SMC) inference engine.'
repo_url: https://github.com/lawmurray/Birch
repo_name: lawmurray/Birch
edit_uri: ""
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: preference
    primary: white
    accent: blue
plugins:
  - search
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
extra_css:
  - 'https://unpkg.com/mermaid@8.5.1/dist/mermaid.css'
extra_javascript:
  - 'https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lawmurray
