version: 2.1

orbs:
  slack: circleci/slack@4.12
  codecov: codecov/codecov@3.2

executors:
  opensuse-bench:
    docker:
      - image: lawmurray/birch-circleci:opensuse
    resource_class: large
    environment:
      OMP_NUM_THREADS: 4
      CXXFLAGS: "-O3 -march=native -flto -Wall"
      MAKE_FLAGS: "-j8"
      LIB_FLAGS: "--disable-assert"
      BIRCH_FLAGS: "--unit=dir --arch=native --jobs=6 --enable-verbose --disable-assert --disable-debug --disable-static --disable-single"
      # ^ --unit here also affects source tarballs deployed to packages
    working_directory: /root/project/opensuse-bench

  opensuse-cover:
    docker:
      - image: lawmurray/birch-circleci:opensuse
    resource_class: large
    environment:
      OMP_NUM_THREADS: 4
      CXXFLAGS: "-O0 -g -Wall -fno-inline --coverage"
      MAKE_FLAGS: "-j8"
      BIRCH_FLAGS: "--unit=unity --jobs=6 --enable-verbose --enable-coverage --disable-optimize --disable-static --disable-single"
    working_directory: /root/project/opensuse-cover

  alpine:
    docker:
      - image: lawmurray/birch-circleci:alpine
    resource_class: large
    environment:
      OMP_NUM_THREADS: 4
      CXXFLAGS: "-O0 -Wall"
      MAKE_FLAGS: "-j8"
      BIRCH_FLAGS: "--unit=unity --jobs=6 --enable-verbose --disable-optimize --disable-static --disable-single"
    working_directory: /root/project/alpine

  archlinux:
    docker:
      - image: lawmurray/birch-circleci:archlinux
    resource_class: large
    environment:
      OMP_NUM_THREADS: 4
      CXXFLAGS: "-O0 -Wall"
      MAKE_FLAGS: "-j8"
      BIRCH_FLAGS: "--unit=unity --jobs=6 --enable-verbose --disable-optimize --disable-static --disable-single"
    working_directory: /root/project/archlinux

  debian:
    docker:
      - image: lawmurray/birch-circleci:debian
    resource_class: large
    environment:
      OMP_NUM_THREADS: 4
      CXXFLAGS: "-O0 -Wall"
      MAKE_FLAGS: "-j8"
      BIRCH_FLAGS: "--unit=unity --jobs=6 --enable-verbose --disable-optimize --disable-static --disable-single"
    working_directory: /root/project/debian

  fedora:
    docker:
      - image: lawmurray/birch-circleci:fedora
    resource_class: large
    environment:
      OMP_NUM_THREADS: 4
      CXXFLAGS: "-O0 -Wall"
      MAKE_FLAGS: "-j8"
      BIRCH_FLAGS: "--unit=unity --jobs=6 --enable-verbose --disable-optimize --disable-static --disable-single"
    working_directory: /root/project/fedora

  ubuntu:
    docker:
      - image: lawmurray/birch-circleci:ubuntu
    resource_class: large
    environment:
      OMP_NUM_THREADS: 4
      CXXFLAGS: "-O0 -Wall"
      MAKE_FLAGS: "-j8"
      BIRCH_FLAGS: "--unit=unity --jobs=6 --enable-verbose --disable-optimize --disable-static --disable-single"
    working_directory: /root/project/ubuntu

  mac:
    macos:
      xcode: 13.4.1
    environment:
      OMP_NUM_THREADS: 4
      CXXFLAGS: "-O0 -Wall"
      MAKE_FLAGS: "-j8"
      BIRCH_FLAGS: "--unit=unity --jobs=6 --enable-verbose --disable-optimize --disable-static --disable-single"
    working_directory: /Users/distiller/project/mac

commands:

  environment:
    parameters: 
      os:
        type: string
    steps:
      - when:
          condition:
            equal: [ mac, << parameters.os >> ]
          steps:
            - restore_cache:
                key: homebrew
            - run:
                name: Homebrew
                command: |
                    HOMEBREW_NO_AUTO_UPDATE=1 brew remove --force --ignore-dependencies node node@14 tcl-tk  # avoids these being unnecessarily updated as dependents later
                    HOMEBREW_NO_AUTO_UPDATE=1 brew unlink parallel  # conflicts with moreutils
                    HOMEBREW_NO_AUTO_UPDATE=1 brew install coreutils moreutils gnu-time libtool flex boost eigen libomp cairo
                    echo "export PATH=/usr/local/opt/gnu-time/libexec/gnubin:/usr/local/opt/flex/bin:/usr/local/opt/bison/bin:\$PATH" >> $BASH_ENV
            - save_cache:
                key: homebrew
                paths:
                  - /Users/distiller/Library/Caches/Homebrew
      - run:
          name: Environment variables
          command: |
              echo "export VERSION_LONG=`git describe --long || echo`" >> $BASH_ENV
              echo "export VERSION=\`echo \$VERSION_LONG | sed -E 's/v([0-9.]+)-([0-9]+)-g[0-9a-f]+/\1.\2/'\`" >> $BASH_ENV
              echo "export VERSION_SAFE=\`echo \$VERSION | sed -E 's/\./_/g'\`" >> $BASH_ENV
              echo "export PREFIX=$CIRCLE_WORKING_DIRECTORY" >> $BASH_ENV
              echo "export PATH=\$PREFIX/bin:\$PATH" >> $BASH_ENV
              echo "export CPLUS_INCLUDE_PATH=\$PREFIX/include:\$CPLUS_INCLUDE_PATH" >> $BASH_ENV
              echo "export LD_LIBRARY_PATH=\$PREFIX/lib64:\$PREFIX/lib:\$LD_LIBRARY_PATH" >> $BASH_ENV
              echo "export LIBRARY_PATH=\$PREFIX/lib64:\$PREFIX/lib:\$LIBRARY_PATH" >> $BASH_ENV
              echo "export FORMAT=', \"real\": %e, \"user\": %U, \"system\": %S, \"memory\": %M, \"involuntary\": %c, \"voluntary\": %w'" >> $BASH_ENV

  end_if_pull_request:
    steps:
      - run: 
         name: End early if pull request
         command: |
            if [[ -n "$CIRCLE_PR_NUMBER" ]]
            then
              circleci step halt
            fi

  codecov:
    parameters: 
      os:
        type: string
    steps:
      - when:
          condition:
            matches:
              pattern: "^.+-cover$"
              value: << parameters.os >>
          steps:
            - run:
                name: Produce coverage report
                command: lcov --directory . --no-external --capture -o cov.info
            - codecov/upload:
                file: cov.info

  slack:
    steps:
      - slack/status:
          fail_only: true

  build_birch:
    steps:
      - run:
          name: Build birch
          command: |
              cd birch
              cat configure.ac | sed -E "s/0\.0\.0/$VERSION/" | sponge configure.ac
              ./bootstrap
              ./configure --prefix="$PREFIX" $DRIVER_FLAGS || (cat config.log && exit 1)
              make install $MAKE_FLAGS
      - run:
          name: Smoke test birch
          command: |
            cd birch
            if [[ -e smoke.sh ]]
            then
              ./smoke.sh
            fi

  build_library:
    description: Build a C++ library
    parameters:
      package:
        description: Name of the library
        type: string
    steps:
      - run:
          name: Build << parameters.package >>
          command: |
              cd << parameters.package >>
              cat configure.ac | sed -E "s/0\.0\.0/$VERSION/" | sponge configure.ac
              ./bootstrap
              ./configure --prefix="$PREFIX" $LIB_FLAGS || (cat config.log && exit 1)
              make install $MAKE_FLAGS

  build_package:
    description: Build a Birch package
    parameters:
      os:
        type: string
      dir:
        description: Directory containing the package (e.g. libraries)
        type: string
      package:
        description: Name of package (e.g. Standard)
        type: string
    steps:
      - run:
          name: Build << parameters.package >> package
          command: |
              cd << parameters.dir >>/<< parameters.package >>
              echo "version: $VERSION" | cat - birch.yml | sponge birch.yml
              birch install --prefix=$PREFIX $BIRCH_FLAGS || (cat config.log && exit 1)
          no_output_timeout: 30m
      - when:
          condition:
            not:
              matches:
                pattern: "^.+-bench$"
                value: << parameters.os >>
          steps:
            - run:
                name: Smoke test << parameters.package >> package
                command: |
                    cd << parameters.dir >>/<< parameters.package >>
                    birch docs
                    if [[ -e smoke.sh ]]
                    then
                      ./smoke.sh
                    fi
      - when:
          condition:
            matches:
              pattern: "^.+-bench$"
              value: << parameters.os >>
          steps:
            - run:
                name: Unit test << parameters.package >> package
                command: |
                    cd << parameters.dir >>/<< parameters.package >>
                    if [[ -e test.sh ]]
                    then
                      env time --format="$FORMAT" --output=time.txt ./test.sh
                      # ^ env time to use GNU time, not Bash built-in time
                    fi
            - run:
                name: Upload  << parameters.package >> results to MongoDB Atlas
                command: |
                    if [[ -n "$MONGODB_HOST" && -n "$MONGODB_USERNAME" && -n "$MONGODB_PASSWORD" && -n "$VERSION_LONG" ]]
                    then
                      cd << parameters.dir >>/<< parameters.package >>
                      if [[ -e output/test.json ]]
                      then
                        echo '{ "output": ' > mongodb.json
                        cat output/test.json >> mongodb.json
                        if [[ -e time.txt ]]
                        then
                          cat time.txt >> mongodb.json
                        fi
                        echo ", \"branch\": \"$CIRCLE_BRANCH\"" >> mongodb.json
                        echo ", \"version\": \"$VERSION_LONG\"" >> mongodb.json
                        echo '}' >> mongodb.json
                        mongoimport --uri mongodb+srv://$MONGODB_USERNAME:$MONGODB_PASSWORD@$MONGODB_HOST/test --collection << parameters.package >> --file mongodb.json
                      fi
                    fi

  brew_identity:
    steps:
      - run:
          name: Configure Homebrew
          command: |
              git config --global user.name "Birch Machine"
              git config --global user.email "birch-machine@indii.org"

  osc_identity:
    steps:
      - run:
          name: Configure OSC
          command: |
              if [[ -n "$OSC_USERNAME" && -n "$OSC_PASSWORD" ]]
              then
                mkdir -p ~/.config/osc
                echo [general]                          > ~/.config/osc/oscrc
                echo apiurl = https://api.opensuse.org >> ~/.config/osc/oscrc
                echo [https://api.opensuse.org]        >> ~/.config/osc/oscrc
                echo user = $OSC_USERNAME              >> ~/.config/osc/oscrc
                echo pass = $OSC_PASSWORD              >> ~/.config/osc/oscrc
              fi

  osc_checkout:
    steps:
      - run:
          name: Checkout Open Build Service repo
          command: |
              if [[ -n "$OSC_PROJECT" && -n "$OSC_USERNAME" && -n "$OSC_PASSWORD" ]]
              then
                osc checkout $OSC_PROJECT
              fi

  osc_commit:
    steps:
      - run:
          name: Commit Open Build Service repo
          command: |
              if [[ -n "$OSC_PROJECT" && -n "$OSC_USERNAME" && -n "$OSC_PASSWORD" && -n "$VERSION" ]]
              then
                cd $OSC_PROJECT
                osc commit -m "Updated to version $VERSION."
              fi

  brew_checkout:
    steps:
      - run:
          name: Checkout Homebrew tap
          command: |
              if [[ -n "$GITHUB_USERNAME" && -n "$GITHUB_PASSWORD" ]]
              then
                git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/lawmurray/homebrew-birch.git
                cd homebrew-birch
              fi

  brew_commit:
    steps:
      - run:
          name: Commit Homebrew tap
          command: |
              if [[ -n "$GITHUB_USERNAME" && -n "$GITHUB_PASSWORD" && -n "$VERSION" ]]
              then
                cd homebrew-birch
                git add -u
                git commit -m "Updated to version $VERSION."
                git push origin master
              fi

  deploy_obs_package:
    parameters:
      dir:
        description: Directory containing the package (e.g. libraries)
        type: string
        default: .
      package:
        description: Name of package (e.g. Standard)
        type: string
    steps:
      - run:
          name: Open Build Service package for << parameters.package >>
          command: |
              shopt -s extglob
              if [[ -n "$OSC_PROJECT" && -n "$OSC_USERNAME" && -n "$OSC_PASSWORD" && -n "$VERSION" ]]
              then
                cd << parameters.dir >>/<< parameters.package >>
                make dist
                TARNAME=`ls *.tar.gz | sed -E s/-$VERSION\.tar\.gz$//`
                mv $TARNAME-$VERSION.tar.gz $CIRCLE_WORKING_DIRECTORY/$OSC_PROJECT/$TARNAME/.
                cd $CIRCLE_WORKING_DIRECTORY/$OSC_PROJECT/$TARNAME
                if ls $TARNAME-!($VERSION).tar.gz > /dev/null
                then
                  osc delete $TARNAME-!($VERSION).tar.gz
                fi
                osc add $TARNAME-$VERSION.tar.gz
                for file in PKGBUILD $TARNAME.spec $TARNAME.dsc debian.control debian.$TARNAME.install debian.$TARNAME-dev.install
                do
                  if [[ -e $file ]]
                  then
                    cat $file |
                      sed -E "s/-[0-9]+\.[0-9.]+?(\.tar\.gz|\.so)/-$VERSION\1/g" |
                      sed -E "s/\%\{name\}-[0-9]+_[0-9_]+/\%\{name\}-$VERSION_SAFE/g" |
                      sed -E "s/Version: [0-9]+\.[0-9.]+/Version: $VERSION/g" |
                      sed -E "s/pkgver=[0-9]+\.[0-9.]+/pkgver=$VERSION/g" |
                      sed -E "s/>= *[0-9]+\.[0-9.]+/>= $VERSION/g" |
                      sed -E "s/== *[0-9]+\.[0-9.]+/== $VERSION/g" |
                      sponge $file
                  fi
                done
              fi

  deploy_brew_package:
    parameters:
      dir:
        description: Directory containing the package (e.g. libraries)
        type: string
        default: .
      package:
        description: Name of package (e.g. Standard)
        type: string
    steps:
      - run:
          name: Homebrew package for << parameters.package >>
          command: |
              shopt -s extglob
              if [[ -n "$GITHUB_USERNAME" && -n "$GITHUB_PASSWORD" && -n "$VERSION" ]]
              then
                cd << parameters.dir >>/<< parameters.package >>
                make dist
                TARNAME=`ls *.tar.gz | sed -E s/-$VERSION\.tar\.gz$//`
                mv $TARNAME-$VERSION.tar.gz $CIRCLE_WORKING_DIRECTORY/homebrew-birch/.
                cd $CIRCLE_WORKING_DIRECTORY/homebrew-birch
                if ls $TARNAME-!($VERSION).tar.gz > /dev/null
                then
                  git rm $TARNAME-!($VERSION).tar.gz
                fi
                git add $TARNAME-$VERSION.tar.gz
                SHA256=($(sha256sum $TARNAME-$VERSION.tar.gz))
                cat $TARNAME.rb |
                  sed -E "s/-[0-9]+\.[0-9.]+\.tar\.gz/-$VERSION.tar.gz/g" |
                  sed -E "s/sha256 \"[0-9a-f]+\"/sha256 \"$SHA256\"/g" |
                  sed -E "s/version \"[0-9]+\.[0-9.]+\"/version \"$VERSION\"/g" |
                  sed -E "s/=> \"[0-9]+\.[0-9.]+\"/=> \"$VERSION\"/g" |
                  sponge $TARNAME.rb
              fi

  deploy_website:
    steps:
      - run:
          name: Deploy website
          command: |
              if [[ -n "$GITHUB_USERNAME" && -n "$GITHUB_PASSWORD" ]]
              then
                git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/lawmurray/docs.birch.sh.git
                make -f mkdocs.makefile
                cp -r mkdocs.yml docs docs.birch.sh/.
                cd docs.birch.sh
                mkdocs gh-deploy
              fi

jobs:
  build:
    parameters: 
      os:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout
      - environment:
          os: << parameters.os >>
      - build_birch
      - build_library:
          package: numbirch
      - build_library:
          package: membirch
      - build_package:
          os: << parameters.os >>
          dir: libraries
          package: Standard
      - build_package:
          os: << parameters.os >>
          dir: libraries
          package: Cairo
      - build_package:
          os: << parameters.os >>
          dir: libraries
          package: SQLite
      - persist_to_workspace:
          root: ..
          paths:
            - << parameters.os >>
      - codecov:
          os: << parameters.os >>
      - end_if_pull_request
      - slack

  test:
    parameters: 
      os:
        type: string
    executor: << parameters.os >>
    steps:
      - attach_workspace:
          at: ..
      - environment:
          os: << parameters.os >>
      - build_package:
          os: << parameters.os >>
          dir: tests
          package: Test
      - codecov:
          os: << parameters.os >>
      - end_if_pull_request
      - slack

  example:
    parameters: 
      os:
        type: string
      package:
        description: Name of package (e.g. LinearRegression)
        type: string
    executor: << parameters.os >>
    steps:
      - attach_workspace:
          at: ..
      - environment:
          os: << parameters.os >>
      - build_package:
          os: << parameters.os >>
          dir: examples
          package: << parameters.package >>
      - codecov:
          os: << parameters.os >>
      - end_if_pull_request
      - slack

  deploy:
    parameters: 
      os:
        type: string
    executor: << parameters.os >>
    steps:
      - end_if_pull_request
      - attach_workspace:
          at: ..
      - environment:
          os: << parameters.os >>

      - osc_identity
      - osc_checkout
      - deploy_obs_package:
          package: birch
      - deploy_obs_package:
          package: numbirch
      - deploy_obs_package:
          package: membirch
      - deploy_obs_package:
          dir: libraries
          package: Standard
      - deploy_obs_package:
          dir: libraries
          package: Cairo
      - deploy_obs_package:
          dir: libraries
          package: SQLite
      - osc_commit

      - brew_identity
      - brew_checkout
      - deploy_brew_package:
          package: birch
      - deploy_brew_package:
          package: numbirch
      - deploy_brew_package:
          package: membirch
      - deploy_brew_package:
          dir: libraries
          package: Standard
      - deploy_brew_package:
          dir: libraries
          package: Cairo
      - deploy_brew_package:
          dir: libraries
          package: SQLite
      - brew_commit

      - deploy_website
      - slack

workflows:
  all:
    jobs:
      - build:
          matrix:
            parameters:
              os: [opensuse-bench,opensuse-cover,alpine,archlinux,debian,fedora,ubuntu,mac]

      - test:
          matrix:
            parameters:
              os: [opensuse-bench,opensuse-cover,alpine,archlinux,debian,fedora,ubuntu,mac]
          requires:
            - build-<< matrix.os >>

      - example:
          matrix:
            parameters:
              os: [opensuse-bench,opensuse-cover]
              package: [Ecology,LinearGaussian,LinearRegression,MixedGaussian,MultiObjectTracking,PoissonGaussian,SIR,VectorBorneDisease]
          requires:
            - test-<< matrix.os >>

      - deploy:
          os: opensuse-bench
          filters:
            branches:
              only:
                - master
          requires:
            - example
            - test
